[project]
name = 'Digital-Identity-System-for-Refugees'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.education-records]
path = 'contracts/education-records.clar'
clarity_version = 2
epoch = 2.5

[contracts.service-authorization]
path = 'contracts/service-authorization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
